### ISSUE TITLE
example.txt not found

### ISSUE THREAD

**Issue by cloudygoose** [cognitiveailab/BYTESIZED32#6]
Hi, 
thank you for sharing the code!

when running scripts/run_code_evaluation.py, i got error that a example.txt is not found...

BYTESIZED32/bytes32/winnability/example.txt

This is from the code:
https://github.com/cognitiveailab/BYTESIZED32/blob/5a52d8e0ca317b30285d7407273f3dc301e66311/bytes32/winnability/language_agent.py#L52

**Comment by PeterAJansen** [comment]
Hi @cloudygoose , thanks for your note.  Judging by the code it looks like a part of the prompt for this agent is included in that external file, that wasn't committed to the repo.  @MarcCote should be able to help commit it, but is currently out on vacation, so it may take a little longer than normal.  Thanks!

**Comment by MarcCote** [comment]
@cloudygoose I added the missing file. try updating the library.
